# Generated by Django 3.2.9 on 2021-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_education_experience_project_reference_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.FileField(default='avatar.png', upload_to='users/profile/'),
        ),
    ]
