# Generated by Django 3.2.9 on 2022-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='IsCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='IsPercent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Score',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
