# Generated by Django 3.2.9 on 2022-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_auto_20220103_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
