# Generated by Django 3.2.9 on 2022-01-03 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0007_alter_education_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOrUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Board Or Universities',
                'db_table': 'BoardOrUniversity',
            },
        ),
        migrations.CreateModel(
            name='CourseOrStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=10)),
                ('Duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'db_table': 'Course Or Stream',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='BoardUniversity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.boardoruniversity'),
        ),
        migrations.AlterField(
            model_name='education',
            name='CourseStream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.courseorstream'),
        ),
    ]
